export const CONST = {
  // Engine
  FIXED_DT: 1 / 30,

  // Player
  PLAYER_SPEED: 4,
  PLAYER_SPRINT_SPEED: 7,
  PLAYER_HEIGHT: 1.7,
  PLAYER_RADIUS: 0.3,
  PLAYER_HP: 3,
  STAMINA_MAX: 100,
  STAMINA_DRAIN: 20,
  STAMINA_REGEN: 10,
  FLASHLIGHT_MAX: 120,
  FLASHLIGHT_DRAIN: 1,
  FLASHLIGHT_RECHARGE: 0.3,

  // Generator
  GENERATOR_FUEL_MAX: 100,
  GENERATOR_FUEL_DRAIN: 1.5,
  GENERATOR_BREAKDOWN_MIN: 60,
  GENERATOR_BREAKDOWN_MAX: 120,
  GENERATOR_REFUEL_AMOUNT: 40,

  // Fence
  FENCE_HP_MAX: 2,
  FENCE_PERIMETER_HALF: 20,
  FENCE_HEIGHT: 2.5,
  FENCE_POST_SPACING: 2,

  // Monster
  MONSTER_ROAM_SPEED: 2,
  MONSTER_INVESTIGATE_SPEED: 2.5,
  MONSTER_HUNT_SPEED: 3.5,
  MONSTER_ATTACK_COOLDOWN: 5,
  MONSTER_RETREAT_DURATION: 12,
  MONSTER_INVESTIGATE_TIMEOUT: 10,
  MONSTER_FENCE_ATTACK_RANGE: 2,
  MONSTER_PLAYER_ATTACK_RANGE: 2,
  MONSTER_PLAYER_DAMAGE: 1,
  MONSTER_AGGRESSION_RATE: 1, // per 10 seconds
  MONSTER_NOISE_THRESHOLD_BASE: 15,

  // Noise
  NOISE_DECAY: 30,
  NOISE_IDLE: 0,
  NOISE_WALK: 10,
  NOISE_SPRINT: 50,
  NOISE_INTERACT: 30,

  // World
  WOODS_RADIUS: 80,
  TREE_COUNT: 250,
  TREE_MIN_RADIUS: 6,
  FUEL_CANISTER_TOTAL: 5,
  FUEL_CANISTER_ACTIVE: 3,

  // Cameras
  CAMERA_RESOLUTION: 128,
  CAMERA_COUNT: 4,

  // Game
  SURVIVE_TIME: 300,
  INTERACTION_RANGE: 2.5,

  // Cabin
  CABIN_WIDTH: 8,
  CABIN_DEPTH: 6,
  CABIN_HEIGHT: 3,
  CABIN_WALL_THICKNESS: 0.15,
} satisfies Record<string, number>;
